### PR TITLE
Feature/route

### LINKED ISSUE #153: Alternative stations page with dropdowns

### PR DESCRIPTION
**Pull request by bmlancien**
@henhuy can you have a look at `route_dropdown.html` and update the station lists?

Fix #153

### CODE REVIEW

**Comment by henhuy** [comment]
Implemented stations for dropdown.
But now, we have to handle if user selects same station for start and end.
This leads to nonsens/failing comparions...
Idea?

**Comment by bmlancien** [comment]
I get this error on `/route_dropdown` after I pulled: `TypeError: 'StationsWidget' object is not iterable`

> Implemented stations for dropdown.
> But now, we have to handle if user selects same station for start and end.
> This leads to nonsens/failing comparions...
> Idea?

A cool thing would be if the user has chosen a station in one of the dropdowns, that the other dropdown gets that station on the fly so we could make that station gray and not selectable. But I imagine this a bit complicated, right?

Otherwise we could simply add an error message popup in case the user has chosen the same stations and tapped on the next button?

**Comment by henhuy** [comment]
Added alert (not nice!) if start and end station are the same...

> I get this error on `/route_dropdown` after I pulled: `TypeError: 'StationsWidget' object is not iterable`

Strange?! Everything is commmited and pushed... Cache?

**Comment by bmlancien** [comment]
> Strange?! Everything is commmited and pushed... Cache?

Now this is working properly... Maybe the cache...

> Added alert (not nice!) if start and end station are the same...

There is no way to style the alert box with CSS. One way recommended is to use [jQuery UI](https://stackoverflow.com/questions/11528845/how-do-i-style-the-alert-box-with-css). But we haven't installed it. Otherwise we can leave it like as it is. I don't see this as having high priority.

**Pull request merged**
