### PR TITLE
Feature/quiz finished

### LINKED ISSUE #314: New congrats page design is missing

### PR DESCRIPTION
**Pull request by bmlancien**
Still to do:
- [x] dynamic flashes and scores
- [x] set the text/score in a correct way, I only added plain text
- [x] update the flash icons section, the HTML is quite ugly right now (it should be kept in two lines like now)
- [x] add the footer

fix #314

### CODE REVIEW

**Comment by henhuy** [comment]
Just saw that flash width is different for green (24px) and white (18px) flashes 
Which looks a bit strange?!

**Comment by henhuy** [comment]
Added footer to page but it appears in the middle of the page - @bmlancien ?!

**Comment by bmlancien** [comment]
> Just saw that flash width is different for green (24px) and white (18px) flashes
Which looks a bit strange?!

I cannot see this... Are you talking about the image files or inside the code?

**Comment by henhuy** [comment]
> Are you talking about the image files or inside the code?

Images on screen - when clicking on "Element untersuchen"

**Comment by bmlancien** [comment]
I don't have this issue (Chrome and Firefox). I changed the images but kept the same file names. Maybe a cache issue?

**Comment by henhuy** [comment]
Sorry - after refreshing cache it's gone... argh!

**Comment by bmlancien** [comment]
@henhuy I have moved the footer to the bottom. Can you have a look?

It should be possible to tap on "Quiz" (footer) and go to the dashboard. And since finished-page is not part of the quiz/dashboard, this element should not be highlighted. Can you take care of that too?

**Comment by henhuy** [comment]
> @henhuy I have moved the footer to the bottom. Can you have a look?
> 
> It should be possible to tap on "Quiz" (footer) and go to the dashboard. And since finished-page is not part of the quiz/dashboard, this element should not be highlighted. Can you take care of that too?

thanks! - yes, I will adapt quiz icon

**Comment by henhuy** [comment]
Now, share icon on dashboard leads to finished page, if quiz is finished.
Is this good? Or does it confuses the user?

**Comment by bmlancien** [comment]
As a user I would expect to have the possibility to share directly without going through another page (here the congrats page). What do you think about simply using a popup like on congrats page with the same social media icons but with also the number of points + the (funny) slogan? That would show the user what he/she will be sharing.

**Comment by henhuy** [comment]
> As a user I would expect to have the possibility to share directly without going through another page (here the congrats page). What do you think about simply using a popup like on congrats page with the same social media icons but with also the number of points + the (funny) slogan? That would show the user what he/she will be sharing.

Jepp this is better - I will start functionality, but need your help maybe...

**Comment by henhuy** [comment]
Implemented functionality - now you have to fix design...

**Comment by bmlancien** [comment]
> Implemented functionality - now you have to fix design...

Done! Please have a short look to see if it works properly. Thanks!

**Pull request merged**
