### PR TITLE
Feature/tour

### LINKED ISSUE #225: Implemented tour on dashboard
I will start with an implementation in JS.
Afterwards you can design...

### PR DESCRIPTION
**Pull request by henhuy**
Closes #225

Implemented tour in JS on dashboard.
texts and div classes can be changed on every step of the tour (see js on bottom of dashboard.html)

### CODE REVIEW

**Comment by henhuy** [comment]
@bmlancien, could you add classes and texts for the tour?

**Comment by henhuy** [comment]
> @henhuy Is there a way to work on the tour without having to restart the quiz each time? Clearing the cache doesn't seem to be working.

In firefox you can go to developwer tools->web-Speicher and there you can delete cookie "sessionid"...

**Comment by henhuy** [comment]
> I added new texts. About the classes, do you mean for each box or do you mean the elements that should be targeted?

I meant for each box...
Do you need to style targets differently?

**Comment by bmlancien** [comment]
> Do you need to style targets differently?

I would like the boxes to be displayed like tooltips or something similiar so that the user can associate the text with the correct location (dashboard, footer button, etc.). Is it possible?

**Comment by henhuy** [comment]
> I would like the boxes to be displayed like tooltips or something similiar so that the user can associate the text with the correct location (dashboard, footer button, etc.). Is it possible?

I thought you could position them via styling?
Or does it need to be done in JS?

**Comment by bmlancien** [comment]
> I thought you could position them via styling?
> Or does it need to be done in JS?

I can try with CSS, but that I will be using approximate distances to add an arrow pointing to a button for example. I can maybe try using screen width percentages... 

Did you have a look at this? https://get.foundation/sites/docs-v5/components/joyride.html
I don't know if it's a good idea, the github seems a bit outdated: https://github.com/zurb/joyride

**Comment by henhuy** [comment]
Joyride really seems outdated (though it would have been nice).

As a different approach, I also could show/hide divs given by an id, if that makes it easier for you??

**Comment by bmlancien** [comment]
Yeah, give an id for each div and i will try to work with that. If not, I come back to you :)

**Pull request closed without merging**
