### PR TITLE
add new dashboard icons with bvg black color

### PR DESCRIPTION
**Pull request by bmlancien**
@henhuy I would like to change the new icons that I just added but can't find the file to update them. Is that questions.cfg?

### CODE REVIEW

**Comment by henhuy** [comment]
> @henhuy I would like to change the new icons that I just added but can't find the file to update them. Is that questions.cfg?

correct!

**Comment by bmlancien** [comment]
Ah! After restarting the app I can see the new icons. You can merge the branch if that looks good to you.

**Comment by henhuy** [comment]
I think you missed two icon files `i_e_bus_black.svg` and `i_person_black.svg`?

**Comment by bmlancien** [comment]
Icons added!

**Pull request merged**
