### PR TITLE
New answer design

### LINKED ISSUE #372: Answer page should be removed
- The selected, right and wrong answers should be visible using different colors
- The answer page should be removed
- Instead there should be 2 options visible on the question page after answering :
  - Button "next question" -> next question
  - Button "learn more" -> dropdown full answer text

### PR DESCRIPTION
**Pull request by henhuy**
Closes #372

### CODE REVIEW

**Comment by henhuy** [comment]
Added flashes to answer page.
Added "!" to current flash - so you can style this one (animation?)
Added class attributes "correct" and "answered" (by user) to every question.
Is this sufficient for you, @bmlancien ? Do you need anything else?

**Comment by bmlancien** [comment]
> Is this sufficient for you, @bmlancien ? Do you need anything else?

I think so far that's enough for me. I might come back to you once I have finished the design. Thanks!

**Comment by bmlancien** [comment]
The colors are there.

I think it would be best to keep the question on the answer view. Since the question is in a form, I don't know if I would do it correctly. Could you do this?

I added "see more" below the answers (and not next to the "next question" button). I think it's actually the easiest way to display the full answer text. Could you change the wording when it's active to "hide" or something similar?

> Added "!" to current flash - so you can style this one (animation?)

Is it for the data source that should be linked to some questions (see #377)?

**Comment by henhuy** [comment]
Added original question.
"More" button changes label.

> Is it for the data source that should be linked to some questions?

No, I meant, if you want to animate the new flash to (like the score on dashboard in a previous version - make big and small)...

**Comment by bmlancien** [comment]
As an alternative we could do this:

1st page: Add "see more" button (very decent color)

Question_answered (2)

2nd page: It would link to another page (yes, that means they would have two steps to do instead of one to go to the next question, but since most of users are apparently not so interested in reading the texts, I don't see this as problematic). The "next" button would be exactly the same as the last page. Would it be possible to make the back icon on the top-nav go back to the 1st page though?

Question_answered (3)

**Comment by bmlancien** [comment]
> No, I meant, if you want to animate the new flash to (like the score on dashboard in a previous version - make big and small)...

I see. I think I would rather animate the correct answer(s). I would not make 2 animations on that same page, so probably not.

**Comment by henhuy** [comment]
Do you have everything you need, @bmlancien ?

**Comment by bmlancien** [comment]
> Do you have everything you need, @bmlancien ?

I did a few changes but I still need a few things:

- Do you know how I could select all the answers that are not the correct answer(s)? I want to make them lighter but only once the user has answered (that means the answer view and not the question view)
- Could you remove "!" between the flashes?
- The order of content inside "see more" should be:
  - short answer
  - picture
  - long answer

**Comment by henhuy** [comment]
>     * Do you know how I could select all the answers that are not the correct answer(s)? I want to make them lighter but only once the user has answered (that means the answer view and not the question view)

Mey with the [_not_](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)?
Selector should be something like: `:not(correct) answered`

>     * Could you remove "!" between the flashes?

Done
Changed order of answer as well.

**Comment by bmlancien** [comment]
@henhuy can you have a look? It should be working now

**Comment by henhuy** [comment]
Looks very nice now! Good job :+1: Merge?

**Pull request merged**
