### PR TITLE
Implemented multiple comparisons for environment page

### LINKED ISSUE #299: 'My route' page's content is not optimal
The chart from comparison will be used on that page too with the following components:

- CO2
- NOx
- particulate matter

for comparing 

- own route
- fleet

To do:

@henhuy 
- [x] functionality

@bmlancien 
- [x] mockup
- [ ] HTML/CSS

### PR DESCRIPTION
**Pull request by henhuy**
Closes #299

### CODE REVIEW

**Comment by henhuy** [comment]
Implemented functionality.
Needs (much) design ;) 
thx, @bmlancien

**Comment by henhuy** [comment]
Did following things:
- Tabs get active on selection
- Chart icons are rendered correctly
- Charts are loaded dynamically (ajax) on demand

@bmlancien : Could you redesign/replace the loader? (grabbed one from web)
Do you think we should implement dynamic loading of chart for comparison page as well?

**Comment by bmlancien** [comment]
@henhuy Super, it already looks better!

> Could you redesign/replace the loader? (grabbed one from web)

I changed the loader a bit and centered it.

There are 3 more things though (point 3 is less important):

- After loading, even if you were at the bottom of the page (so you can see the whole chart) it scrolls up automatically to the top of the page. An idea would be to force the page to stay at the bottom of the page after loading?
- When there are 3 values at 0, the trophies should be 1, 1, 1 (with a black one for e-bus) and not 1, 2, 3
- Is it possible to move down the trophies a bit? They are a bit far away from the bars. I think we already talked about it, I can't remember

> Do you think we should implement dynamic loading of chart for comparison page as well?

I think it's a good idea, also because it will give the users the feeling that they're leaving the onboarding/carousel and that they are going to see something different

**Comment by henhuy** [comment]
Adapted trophy offset. If you want to play with it you have to change `TROPHY_OFFSET` variable in _charts.py_

**Comment by henhuy** [comment]
>     * After loading, even if you were at the bottom of the page (so you can see the whole chart) it scrolls up automatically to the top of the page. An idea would be to force the page to stay at the bottom of the page after loading?

I think this is something you have to implement...
the effect occurs due to small loading icon - thus, page resizes to smaller div.
Maybe you have to fix div height somehow?!
Or how can I help?

**Comment by bmlancien** [comment]
> the effect occurs due to small loading icon - thus, page resizes to smaller div.
Maybe you have to fix div height somehow?!
Or how can I help?

Right! I did not think of that. I set the height of the div to a fix height which seems to fit the chart's height. Do you know if the chart's height changes? If that's the case, a fixed height could be an issue.

**Comment by henhuy** [comment]
Currently, chart sizes are fixed to: 
`style="height:55vh; width:100vw;"`

Good? Or should we change it somehow?

**Comment by bmlancien** [comment]
> Good? Or should we change it somehow?

It's been working fine so far, so let's keep it that way. I updated the height to 55vh.

**Pull request merged**
