### PR TITLE
Feature/new mobile lp

### LINKED ISSUE #528: Update mobile LP

### PR DESCRIPTION
**Pull request by bmlancien**
close #528

### CODE REVIEW

**Comment by henhuy** [comment]
Saw one thing: Cookie-Button stays on top when scrolling

**Comment by bmlancien** [comment]
@henhuy I fixed the cookie banner thing and wrote 'CO2' properly

**Comment by henhuy** [comment]
implemented default stations (start and end station of the bus), if user skips onboarding...
Okay ?

**Comment by bmlancien** [comment]
> implemented default stations (start and end station of the bus), if user skips onboarding...
Okay ?

Yep! Thanks

**Pull request merged**
