### PR TITLE
add lanscape view

### PR DESCRIPTION
**Pull request by bmlancien**
@henhuy I added a basic landscape view. for the whole app.. It's not perfect, and I don't think we should spend much time on that, since our app is optimized for portrait view. But what do you think? The chart is not optimal now though...

### CODE REVIEW

**Comment by henhuy** [comment]
I think it is a good idea...
Then we totally get rid of the problem.
Maybe, we could add a one-time banner saying "app is not optimized for landscape view, If you want to get whole experience, please change to portrait mode"?!

**Comment by bmlancien** [comment]
> Maybe, we could add a one-time banner saying "app is not optimized for landscape view, If you want to get whole experience, please change to portrait mode"?!

Is there a way to do check when landscape has been used for the first time? Because I don't want to add that extra text on portrait view. There is already a lot of info on the LP.

**Comment by henhuy** [comment]
hmm. you are right. maybe too much.
and a constant little banner is annoying, right?

**Comment by bmlancien** [comment]
> and a constant little banner is annoying, right?

Yeah, I would not do this... I think if we cannot add a popup which is only displayed the first time the landscape view is active, we should let it that way.

**Comment by henhuy** [comment]
okay - so I will fix merge-conflict and then merge?

**Comment by bmlancien** [comment]
Alright! Thanks!

**Comment by henhuy** [comment]
Now it should work!
Saw one more design thing for landscape view - will post extra issue

**Pull request merged**
