### PR TITLE
Feature/bug feedback

### LINKED ISSUE #266: Implement bug feedback
How can users give feedback to bugs?
Where should it be placed?

### PR DESCRIPTION
**Pull request by henhuy**
Closes #266 

Implemented bug report with 3 different bug types.
Added link to info (legal) page.

### CODE REVIEW

**Comment by bmlancien** [comment]
@henhuy I'm not sure about the usability of having these 3 select options. I would rather have something similar to the following structure (dropdown and then prepopulating a textarea with a different text according to the issue):

- 'Technisches Problem"
  - Textarea: "Etwas funktioniert nicht? Ein Link ist kaputt? Du kannst uns gern das Problem beschreiben."

- 'Schwierigkeit bei der Nutzung der App"
  - Textarea: "Ist etwas schwierig oder frustrierend zu nutzen? Du kannst das gern hier genauer beschreiben."

- 'Inkorrekter oder unverständlicher Inhalt'
  - Textarea: "Um welchen Inhalt geht es?"

- 'Anderes'
  - Textarea: "Kannst du uns dein Problem beschreiben?"

What do you think?

Other thing: we were actually talking yesterday about using tabs also on the info page. "Submit feedback/bug" would be a tab too and we would not need to put that form on an extra page. But this will come into another issue.

**Comment by bmlancien** [comment]
@henhuy I have pushed one commit

**Comment by henhuy** [comment]
> What do you think?

I think this is a good idea!
I will implement it.

**Comment by henhuy** [comment]
Hey @bmlancien, I implemented your suggestion. Can you review? thx

**Comment by bmlancien** [comment]
I did a small change to the text

Is it possible to change the text inside the textarea tags into [placeholders](https://stackoverflow.com/questions/108207/how-do-i-make-an-html-text-box-show-a-hint-when-empty) instead?

**Comment by henhuy** [comment]
> Is it possible to change the text inside the textarea tags into [placeholders](https://stackoverflow.com/questions/108207/how-do-i-make-an-html-text-box-show-a-hint-when-empty) instead?

Nice idea! Done.

Now, only thing left is design for link-to-bug on legal page. Or do you want to skip this in favor of redesigning legal page with tabs?

**Comment by bmlancien** [comment]
> Now, only thing left is design for link-to-bug on legal page. Or do you want to skip this in favor of redesigning legal page with tabs?

Yes, I think it is better to make a new issue for re-designing the legal page first.

**Pull request merged**
