### PR TITLE
Feature/imprint

### LINKED ISSUE #301: Imprint tab in legal page is missing

### PR DESCRIPTION
**Pull request by bmlancien**
@henhuy I added the imprint and privacy content into the mobile app. I'm not sure anymore about how to create a new page for destkop. Could you create `imprint.html` and `privacy.html` and I would have a look afterwards? And what about having the imprint/privacy content somewhere else and inject it on both mobile and desktop? Oherwise we would have the same content twice.

fix #301

### CODE REVIEW

**Comment by henhuy** [comment]
For me, it would be much easier to use a reveal for imprint and privacy on desktop landing page.
Okay with this? Or do they need an extra page?

**Comment by henhuy** [comment]
> And what about having the imprint/privacy content somewhere else and inject it on both mobile and desktop?

Done! Content is included and not doubled.

**Comment by bmlancien** [comment]
> For me, it would be much easier to use a reveal for imprint and privacy on desktop landing page.
Okay with this, @bmlancien ? Or do they need an extra page - this is also fine...

This is not very usual I think to do it that way, but we can try. I would have to adjust the reveal a bit.

**Comment by henhuy** [comment]
"not very usual" - so should we put it on extra page for convenience? (is okay as well for me)

**Comment by bmlancien** [comment]
I mean, as a user I don't think I expect to have a popup when clicking on imprint or privacy. It depends how much work it is for you. These pages are not our priorities.

**Comment by henhuy** [comment]
ok then, I will implement it as reveal for the moment.

**Comment by henhuy** [comment]
Implemented privacy and imprint reveals on desktop page. Your turn, @bmlancien ;)

**Comment by bmlancien** [comment]
@henhuy Done! Can you have a look?

**Pull request merged**
