### PR TITLE
Score can be saved and shared via link

### LINKED ISSUE #16: Scores are stored and can be linked
Idea:
- Save score with date and hash
- link contains hash 
- page is loaded if hash matches db entry

### PR DESCRIPTION
**Pull request by henhuy**
Closes #16 

Todos:
- [x] Add model to save score and connected hash
- [x] Add view and template to save/share score
- [ ] Layout score template
- [ ] Include typical sharing apps (telegram?, etc.)

### CODE REVIEW

**Comment by henhuy** [comment]
Updated finished page to show share link.
@bmlancien could you design the share link?

**Comment by bmlancien** [comment]
> @bmlancien could you design the share link?

@henhuy Do you mean this?

Share_Score

**Comment by henhuy** [comment]
Ah yes - we don't know yet how to implement different platforms, right?
I can look into that and implement it.
Sorry for bothering you again...

**Comment by bmlancien** [comment]
No worries! 
I have no clue how to implement the platforms... And if we need to prioritize, I think the most important platform would be FB.

**Pull request merged**
