### PR TITLE
Data infos

### LINKED ISSUE #139: Info about data is missing
Add info to: 

- comparison page (as popup)
- info page

### PR DESCRIPTION
**Pull request by bmlancien**
Added link and pop-up to comparison page.
Added dummy table to pop-up and info page.

@henhuy I didn't know how the data looks like, so I just added a table. Is that fine or should I change it to something else?

fix #139

### CODE REVIEW

**Comment by henhuy** [comment]
There is an ugly error when hovering closing button:
grafik

Do you need more infos to fix it?

**Comment by bmlancien** [comment]
Ah yeah, I already saw that. But I thought I had fixed it. If it's not because of your cache I will check this later!

**Comment by henhuy** [comment]
> Ah yeah, I already saw that. But I thought I had fixed it. If it's not because of your cache I will check this later!

Just saw that this still needs to be fixed.
Additionally, tob bar is greyed somehow?!
grafik

**Comment by henhuy** [comment]
Added data from tim. 
But now table is very big. Any ideas?
Added source as well - could you make it shiny?

**Comment by bmlancien** [comment]
> There is an ugly error when hovering closing button

Do you still have that error? I don't have it

**Comment by bmlancien** [comment]
> Just saw that this still needs to be fixed.
Additionally, tob bar is greyed somehow?!

I also can't see this. I've checked on Chrome and Firefox

**Comment by henhuy** [comment]
> > Just saw that this still needs to be fixed.
> > Additionally, tob bar is greyed somehow?!
> 
> I also can't see this. I've checked on Chrome and Firefox

Still see both errors. Maybe you missed pushing some diffs?
Or my css wont update somehow...
Dont know.

**Comment by bmlancien** [comment]
What should I push?

**Pull request merged**
