### PR TITLE
Refactored summary into static page

### LINKED ISSUE #396: Summary page not ready
TODOs:
- [ ] Pictures for all questions
- [ ] Nice labels for all questions
- [ ] Text from long answers?

### PR DESCRIPTION
**Pull request by henhuy**
Closes #396

### CODE REVIEW

**Comment by henhuy** [comment]
Content has to be filled

**Comment by bmlancien** [comment]
@henhuy I get that error on display_route:

**Comment by henhuy** [comment]
You have to flush cache - this is due to "new" implementation of answers in session (from other branch)

**Comment by bmlancien** [comment]
> You have to flush cache - this is due to "new" implementation of answers in session (from other branch)

Done!

**Pull request merged**
