### PR TITLE
Implemented mobile check to switch between desktop and mobile app

### LINKED ISSUE #417: Landscape message should not be visible on desktop

### PR DESCRIPTION
**Pull request by henhuy**
Closes #417

### CODE REVIEW

**Comment by henhuy** [comment]
Deploy is running.

And you are right - now we cannot test mobile version in browser..
I will write a workaround for "local" debug mode...

**Comment by henhuy** [comment]
Deployed - Now we can test!

**Comment by henhuy** [comment]
Works!
But sometimes I see desktop version for a short moment - I will fix it!

**Comment by bmlancien** [comment]
@henhuy should we merge?

**Pull request merged**
