### PR TITLE
Fix/lp animation

### LINKED ISSUE #498: Animation on desktop LP does not properly

### PR DESCRIPTION
**Pull request by bmlancien**
@henhuy For some reason the animation on scroll down on desktop LP was not working properly anymore (items should show up when visible in the window when scrolling down). I think I fixed it. Can you have a look? The "Zusammenfassung" page on the app should not have any animation though.

fix #498

### CODE REVIEW

**Review by henhuy — CHANGES_REQUESTED** [review]
Major parts of desktop page are blank for me.
Maybe this is due to latest updates (desktop page is loaded later dynamically only if needed).
Could you merge current dev and check if you can see same error?

**Comment by bmlancien** [comment]
After merging from dev I can't find the same error than you on Chrome and Firefox... But the tests apparently failed too. It's not an emergency though, so we can wait until finding a better solution.

**Comment by henhuy** [comment]
tests fail for a minor reason (not including your changes)

**Comment by henhuy** [comment]
hmm - tested again - now it's working!

**Pull request merged**
