### PR TITLE
Feature/new display route

### LINKED ISSUE #527: Display-route should be on a single page

### PR DESCRIPTION
**Pull request by bmlancien**
close #527

### CODE REVIEW

**Comment by henhuy** [comment]
Nice!
One remark:
things are left-aligned - when screen is wider, this looks a bit strange?!

**Comment by henhuy** [comment]
e-PKW and Dieselbus same CO2 ?!

**Comment by bmlancien** [comment]
@henhuy 
> e-PKW and Dieselbus same CO2 ?!

Should be fixed

**Review by henhuy — CHANGES_REQUESTED** [review]
I like the new style.
One minor thing: 
If line is short, CO2 in g is shown right of percentage, in other cases is shown below:
grafik

Should we make it consistent?

**Comment by henhuy** [comment]
And for some reason the integration test failed? - I will check it!

**Comment by bmlancien** [comment]
> If line is short, CO2 in g is shown right of percentage, in other cases is shown below:

This is what I have if I use the Chrome emulator. It's using iPhone 5, which supposedly has the smallest width (320px) of most phones. Maybe we could just test it on a real device (trying to find a small one) and make changes if this is really an issue?

localhost_3000_meine-strecke_(iPhone 5_SE)

**Pull request merged**
