### PR TITLE
Feedback page

### LINKED ISSUE #122: Feedback page doesn't exist
Create feedback page including 3-4 questions for users. Add possibility to give stars and to write text (like Airbnb app)

- [x] Mockup
- [x] Implementation
- [ ] Redirect to feedback view after 2sec @ finished view
- [x] Implement stars as JS

### PR DESCRIPTION
**Pull request by bmlancien**
fix #122

### CODE REVIEW

**Comment by henhuy** [comment]
still in progress, or not?
cannot change stars yet...

I will integrate it with database model, once you finished form and when we know how where/when to show feedback page...

**Comment by bmlancien** [comment]
It's done. We can show it to Tim and he will tell us if that's fine for him.

**Comment by henhuy** [comment]
Hey @bmlancien , what do you mean with
> It's done

I cannot change stars? something wrong or did I misunderstood?

**Comment by bmlancien** [comment]
Hi @henhuy Sorry, I meant, the static layout implementation is done, @mdrli took care of it :) So you can work on your side!

**Comment by henhuy** [comment]
Integrated db models into feedback page.
Unfortunately, feedback form look slightly different.
Could you have a look, @mdrli or @bmlancien ?!
Layout for stars and comment widget can be found at 
`e_metrobus/templates/widgets/feedback_comment.html` and 
`e_metrobus/templates/widgets/feedback_stars.html`

**Comment by bmlancien** [comment]
@henhuy since @mdrli is not on that project anymore, I did the design changes :)

**Comment by henhuy** [comment]
Hey @bmlancien,
solved feedback stars with inline SVG - but now stars are bigger than before...
Could you help one last time?

**Comment by henhuy** [comment]
Had to change "Überspringen" to submit button instead of link - now it looks different than before. Could you fix? sorry ;)

**Comment by bmlancien** [comment]
@henhuy no worries! I did the changes, can you just check that everything works fine? If yes, we could just merge.

**Pull request merged**
