### PR TITLE
Enabled route dropdown as default

### LINKED ISSUE #195: Enable route dropdown

### PR DESCRIPTION
**Pull request by henhuy**
Closes #195

### CODE REVIEW

**Comment by bmlancien** [comment]
fix #200

**Comment by henhuy** [comment]
Is it fixed?

**Comment by bmlancien** [comment]
It is fixed, but now the other pages have the same issue again. The changes from yesterday are probably not included in that branch.

**Comment by henhuy** [comment]
Yep - that's right!
So I will merged them all.
Thx

**Pull request merged**
