### PR TITLE
Added E-PKW to data and chart

### LINKED ISSUE #224: Comparison chart: Combine feed and bike; add E-PKW

### PR DESCRIPTION
**Pull request by henhuy**
Closes #224

### CODE REVIEW

**Comment by henhuy** [comment]
Added E-PKW to data and chart.
Three things you could do, @bmlancien :
- Now, we need chart icon for combined pedestrian/bike
- Chart & display route Icon for E-PKW
- On my screen, there is much unused space between chart and button (do I have to change, or you?)

**Comment by bmlancien** [comment]
@henhuy I added the new icons and also updated a few of them on route_display. You just have to update the combined pedestrian/bike icon from the chart.

Is there a way to change/add CSS classes from `<main class="grid-x main-content">` in `base.html`? I've seen that it is possible with `<body class="{% block body_class %}l-scroll l-scroll--nav{% endblock %}">`. If I can add an extra class, I could update the layout on the comparison page.

**Comment by bmlancien** [comment]
@henhuy is there a way to break "Zu Fuß/Fahrrad" into 2 lines? It is pushing the graph to the right...

**Comment by henhuy** [comment]
like this?

**Comment by henhuy** [comment]
Did you fixed/changed this?
> On my screen, there is much unused space between chart and button (do I have to change, or you?)

On my screen it looks like this:
grafik

Are you fine with it?

**Comment by bmlancien** [comment]
> Are you fine with it?

Yes, it's not a problem to have some white space. That way, the chart is more prominent.

**Pull request merged**
