### PR TITLE
Adapted new icon sizes and font colors

### LINKED ISSUE #183: Results on comparison chart is not understandable enough
localhost_3000_comparison_(iPhone 6_7_8) (1)

### PR DESCRIPTION
**Pull request by henhuy**
Closes #183

### CODE REVIEW

**Comment by bmlancien** [comment]
@henhuy I think the text looks better like that. There are still few things I would like to change:

- The trophies are too high (see screenshot)
- I created new icons (the 5 transportation options). Can you replace them and give them the same size? If everything works properly, the e-bus icon should look larger than the other ones
- Can you replace the e-bus bar black color with our yellow color? (sorry, I think you already changed it several times...)

localhost_3000_comparison_(iPhone 6_7_8 Plus)

**Comment by henhuy** [comment]
Hey @bmlancien,
I added new icons and set e-bus bar to BVG yellow.
But for me trophys are correct?!
grafik

Could you tell me your (mobile) screen resolution (width/height), so I can test?

**Comment by henhuy** [comment]
Maybe, changing of icons led to new sizes - perhaps it is okay now?

**Comment by bmlancien** [comment]
I've positioned the black button a bit better and I've changed again the icons, but the file names are the same, you just need to pull.

The trophies are still too high on the chart though. Can you move them down?

**Comment by bmlancien** [comment]
> Could you tell me your (mobile) screen resolution (width/height), so I can test?

All of them...

Maybe the cache. I'll try that

**Comment by bmlancien** [comment]
Cleared the cache but nothing changed. I tested in Firefox and it works properly. Maybe this problem is just on Chrome.

**Comment by henhuy** [comment]
Chrome is also fine for me?! Very strange

**Comment by henhuy** [comment]
I will merge changes for now, and create new issue...

**Pull request merged**
