### PR TITLE
Share buttons

### PR DESCRIPTION
**Pull request by henhuy**
Added share buttons to finished quiz page
(To see buttons while quiz is not yet finished, I added some dev-fixes which have to be removed before push)

TODO:
- [x] Remove "FIXME"

### CODE REVIEW

**Comment by henhuy** [comment]
@bmlancien could you check design?
I added input field with share link which is copied to clipboard by clicking on sahre button.
Your ideas?

**Comment by bmlancien** [comment]
@henhuy I put the icons in a reveal to keep the congrats page simpler. I commented out the copy button and added a copy icon instead, but there is no functionality. Can you add it (i.e. copy to clipboard functionality)? One good thing would be to give feedback to the user that the link has been copied. An example: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard2 (I would not show the text in an input box though, just some feedback like "Link has been copied" or something similar)

**Comment by henhuy** [comment]
Activated copy to clipboard again
Tooltip did not work well - so I added simple div (which is showed for 600ms and hidden afterwards).
Could you check, @bmlancien ?

**Comment by henhuy** [comment]
Saw your change! Nice!
Shall we push?

**Comment by bmlancien** [comment]
Yes!

**Pull request merged**
