### PR TITLE
Non bus users

### LINKED ISSUE #316: User-flow for non-bus users is missing
@henhuy Now we only have one user-flow (bus users):

Landing page -> onboarding -> single-page tour -> dashboard -> offboarding

It is thought for users that will be sitting inside the bus. But we also have to think about the users that will receive the app link from other users. Meaning that they probably won't be using a bus when receiving the link. In that case it doesn't make sense to ask them to select a route. But they still should be able to use the app. For them (non-bus users) the user-flow should be the following:

Landing page -> single-page tour -> dashboard -> offboarding

- The single-page tour wording should be slightly different.
- "My route" page should display a default route (but they still should be able to change the route if they want to).

What would be the best approach for implementing this? Using two different URLs?

### PR DESCRIPTION
**Pull request by henhuy**
Closes #316 

Todos:
- [x] add landing page URL for non-bus-users [NBU]
- [x] add default route for NBUs
- [x] add different "tour" for NBUs
- others?

### CODE REVIEW

**Comment by henhuy** [comment]
I set whole route length as default (from Hertzallee to Michelangelostr.), what do you think?
Added /welcome/ url for NBUs - Text already changed to "Toll, dass du dich für den E-Bus interessierst" and onboarding is skipped when using this landing page...

**Comment by bmlancien** [comment]
Thank you @henhuy 

> I set whole route length as default (from Hertzallee to Michelangelostr.), what do you think?

I think it's a good idea!

> Added /welcome/ url for NBUs - Text already changed to "Toll, dass du dich für den E-Bus interessierst" and onboarding is skipped when using this landing page...

Could you also add a different URL for the tour? That's because the text will also be different. Or is it possible to keep the same URL while having 2 different versions?

**Comment by henhuy** [comment]
Added second template "tour_non_bus_users.html" which will be called if NBU visits tour page

**Comment by bmlancien** [comment]
> Added second template "tour_non_bus_users.html" which will be called if NBU visits tour page

The button from `welcome.html` leads to `tour.html` and not to `tour_non_bus_users.html`. Is it normal?

**Comment by henhuy** [comment]
For me it works...
In both cases URL points to `tour.html`, but internally template is switched.
If I follow link, non-bus-user template on tour page is loaded...?!

**Comment by henhuy** [comment]
Added slightly different texts for NBUs at tour page.
Merge?

**Comment by bmlancien** [comment]
Merge!

**Pull request merged**
